
POST http://127.0.0.1:8000/update_vector/ HTTP/1.1
Content-Type: application/json;charset=utf-8

{
  "sysCategory" : [
    {
      
      "subCategory" : [
        {
          "fileStorages" : [
            {
              "fileId" : "file00004",
              "fileName" : "《医学病毒学》知识图谱-231229",
              "storagePath" : "stream/40/86/00106250791926853795844449.docx",
              "fileSuffix" : "docx",
              "publicUrl" : "http:\/\/www.baidu.com\/xxx\/xxx\/xxxpy.txt",
              "fileSize" : "123456"
            }
          ],
          "categoryId" : "234324234",
          "parentId" : "1010010101",
          "categoryName" : "⼆级分类"
        }
      ],
      "categoryId" : "1010010101",
      "parentId" : "0",
      "categoryName" : "⼀级分类",
      "level" : 1
    }
  ],
  "syncId" : "123"
}

